_target_: models.decoder.vqvae.ActionConditionedProjectedVQVAEDecoder
channel: 64
n_embed: 2048
n_res_block: 4
n_res_channel: 128
quantize: false
hidden_dim: 512
num_layers: 2
sg_before_vqvae: true
sg_before_emb_decoder: false
# in_dim injected at runtime from projected_dim
# emb_dim injected at runtime from encoder_emb_dim (384)
# action_dim injected at runtime from dataset.action_dim
