name: 8tasks

dataset:
  _target_: "datasets.multitask_robomimic_dset.load_multitask_robomimic_slice_train_val"
  normalize_action: ${normalize_action}
  with_velocity: true
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}
  tasks:
    - name: lift
      data_path: ${oc.env:TCWM_DATA_ROOT,./data}/robomimic/lift/ph_convert_full
    - name: can
      data_path: ${oc.env:TCWM_DATA_ROOT,./data}/robomimic/can/ph_convert_full
    - name: square
      data_path: ${oc.env:TCWM_DATA_ROOT,./data}/robomimic/square/ph_convert_full
    - name: transport
      data_path: ${oc.env:TCWM_DATA_ROOT,./data}/robomimic/transport/ph_convert_full
    - name: tool_hang
      data_path: ${oc.env:TCWM_DATA_ROOT,./data}/robomimic/tool_hang/ph_convert_full
    - name: point_maze
      data_path: ${oc.env:TCWM_DATA_ROOT,./data}/bmw48/osfstorage/datasets/point_maze
    - name: wall
      data_path: ${oc.env:TCWM_DATA_ROOT,./data}/bmw48/osfstorage/datasets/wall_single
    - name: pusht
      data_path: ${oc.env:TCWM_DATA_ROOT,./data}/bmw48/osfstorage/datasets/pusht_noise

# task embeddings (generated by create_task_embeddings.py)
task_emb_path: /home/minghao.fu/workspace/tcwm/all_tasks.json

decoder_path: null
num_workers: 16
